### ISSUE TITLE
Enchantment ID Blacklist for the Purifier

### ISSUE THREAD

**Issue by Bluberry-Kat** [rubensworks/EvilCraft#855]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:
The Purifier can disenchant tools and remove curses as well.  
This is pretty powerful, depending on the modpack.  
I think it would be nice to have a blacklist for enchantments that the purifier can effect or not.
Proposed format:
```toml
[machine]

	[machine.purifier]
		#Item that can not be disenchanted. Regular expressions are allowed.
		disenchantBlacklist = ["tetra:.*"]
		#Enchantments to be disqualified from disenchantment, or curses disallowed from purification.
		enchantmentIdBlacklist = ["minecraft:vanishing_curse","evilcraft:vengeance"]
```

Potentially `disenchantBlacklist` could be renamed to disambiguate.  
Might be some work, but if it happens, I'd suggest "itemBlacklist"
